version: "2"
linters:
  default: standard
  enable:
    - errcheck
    - errname
    - exhaustive
    - exptostd
    - funcorder
    - gochecksumtype
    - gocritic
    - gosec
    - prealloc
    - recvcheck
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - usestdlibvars
  settings:
    gosec:
      config:
        G306: "0644"
formatters:
  enable:
    - gofumpt
