name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.24'
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-package: 'jre'
          java-version: '21'
      - name: Cache ANTLR JAR
        id: antlr
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: tools/antlr-*.jar
          key: antlr-${{ hashFiles('Makefile') }}
      - name: Install dependencies
        run: make tidy
      - name: Generate
        run: make generate
      - name: Verify generated files are committed
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "::error::Generated files are out of date. Run 'make generate' locally and commit the changes."
            exit 1
          fi
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Integration Test
        run: make test-integration
